# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: alistairmccann
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: my-tickets
# "service" is the name of this project. This will also be added to your AWS resource names.
service: where-its-at

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-north-1
  deploymentMethod: direct

functions:
  GetEvents:
    handler: functions/GetEvents/index.handler
    events:
      - httpApi:
          path: /events
          method: get

  GetTickets:
    handler: functions/GetTickets/index.handler
    events:
      - httpApi:
          path: /events/{id}
          method: get

  PostEvent:
    handler: functions/PostEvent/index.handler
    events:
      - httpApi:
          path: /events
          method: post
